name: social_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.118+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  provider: ^6.1.5
  flutter_webrtc: ^0.14.1
  package_info_plus: ^8.3.1
  http: ^1.1.0
  version: ^3.0.2
  intl: ^0.20.2
  icons_launcher: ^3.0.1
  socket_io_client: ^3.1.2
  path_provider: ^2.1.5
  google_nav_bar: ^5.0.7
  hero_animation: ^1.1.4
  flutter_dotenv: ^5.2.1
  drawerbehavior: ^3.0.4
  mime: ^2.0.0
  file_picker: ^10.2.0
  http_parser: ^4.1.2
  permission_handler: ^12.0.1
  platform_info: ^5.0.0
  hugeicons: ^0.0.11
  video_player: ^2.10.0
  video_player_win: ^3.2.0
  video_player_media_kit: ^1.0.6
  media_kit_libs_windows_video: any
  media_kit_libs_linux: any
  chewie: ^1.12.1
  awesome_notifications: ^0.10.0
  cached_video_player_plus: ^4.0.3
  local_notifier: ^0.1.6
  cached_network_image: ^3.4.1
  video_thumbnail: ^0.5.6
  photo_view: ^0.15.0
  url_launcher: ^6.3.2
  flutter_background: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.3

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/groot_1.jpg
    - assets/logos/logo-senat.png
    - assets/images/bg-senat.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

icons_launcher:
  image_path: "assets/logos/logo-senat.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true
    linux:
      enable: true